version: "3.8"

services:
  upload-mariadb:
    image: mariadb:11    # ‚Üê usar 11.x en vez de 10.5
    container_name: upload_mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - maria-data-upload:/var/lib/mysql
    networks:
      - bridge_upload
    ports:
      - "2700:3306"

  upload-server:
    build: .
    container_name: upload_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./server/uploads:/app/uploads
      - /root/sabesp/files:/files
    networks:
      bridge_upload:
        ipv4_address: 172.25.0.10   # opcional; quita si no quieres IP fija

volumes:
  maria-data-upload:
    driver: local

networks:
  bridge_upload:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
